import {chromium,expect} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const browser=await chromium.launch(),page=await browser.newPage(),results=[];const base='http://localhost:3338';
try{
 for(const width of [1440,1280,1024,768,390]){
  await page.setViewportSize({width,height:1000});await page.goto(base+'/',{waitUntil:'networkidle',timeout:90000});
  const tabs=page.getByRole('tablist',{name:'Product preview'}),frame=page.locator('.showcase-workspace');await tabs.scrollIntoViewIfNeeded();const h=(await frame.boundingBox()).height;
  for(const name of ['02 Screener','03 Asset intel','01 Terminal']){await tabs.getByRole('tab',{name,exact:true}).click();await expect(tabs.getByRole('tab',{name,exact:true})).toHaveAttribute('aria-selected','true');assert.equal((await frame.boundingBox()).height,h);await page.waitForTimeout(220);const active=page.locator('.showcase-panel:not([hidden])');await expect(active).toBeVisible();assert.ok(await active.locator('img').count()>0);await page.screenshot({path:`reports/craft-polish/after/showcase-${name.slice(0,2)}-${width}.png`,fullPage:false});}
  await tabs.getByRole('tab',{name:'01 Terminal',exact:true}).focus();await page.keyboard.press('ArrowRight');await expect(tabs.getByRole('tab',{name:'02 Screener',exact:true})).toBeFocused();
  await page.goto(base+'/screener',{waitUntil:'networkidle'});await page.keyboard.press('/');await expect(page.getByRole('textbox',{name:'Find an asset',exact:true})).toBeFocused();await page.keyboard.type('t/s');assert.equal(new URL(page.url()).pathname,'/screener');await page.keyboard.press('Escape');await expect(page.locator('input[aria-label="Find an asset"]')).not.toBeFocused();
  const helper=page.locator('th .metric-help-trigger').first();await helper.scrollIntoViewIfNeeded();await helper.focus();const tooltip=page.getByRole('tooltip');await expect(tooltip).toBeVisible();await page.waitForTimeout(180);await expect(tooltip).toBeVisible();const b=await tooltip.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=width+1&&b.y>=0&&b.y+b.height<=1000);await page.screenshot({path:`reports/craft-polish/after/tooltip-${width}.png`});await page.keyboard.press('Escape');await expect(tooltip).toHaveCount(0);
  const row=page.locator('.results-surface tbody tr').nth(1);const before=await row.boundingBox();await row.hover();await page.waitForTimeout(160);const after=await row.boundingBox();assert.equal(before.height,after.height);assert.equal(before.x,after.x);
  const href=await page.locator('a[href^="/asset/"]').first().getAttribute('href');await page.goto(base+href,{waitUntil:'networkidle'});const plot=page.locator('.intelligence-plot svg').first();await plot.scrollIntoViewIfNeeded();await plot.focus();await expect(page.locator('.chart-readout').first()).toBeVisible();const text=await page.locator('.chart-readout').first().innerText();await page.keyboard.press('ArrowLeft');assert.notEqual(await page.locator('.chart-readout').first().innerText(),text);await page.screenshot({path:`reports/craft-polish/after/chart-readout-${width}.png`});await page.keyboard.press('Escape');await expect(page.locator('.chart-readout')).toHaveCount(0);
  results.push({width,showcaseStable:true,tabKeyboard:true,searchTypingSafe:true,escape:true,tooltipFits:true,rowStable:true,chartKeyboard:true});console.log(`Interactions passed ${width}`);
 }
}finally{await fs.writeFile('reports/craft-polish/interactions.json',JSON.stringify(results,null,2)+'\n');await browser.close();}
