/**
 * The 100-asset collection universe, as a bundled module.
 *
 * This is a verbatim copy of `assets` in reports/collection-experiment.json,
 * which remains the canonical record of the experiment. The copy exists because
 * application code cannot import from outside `src/` on the build machine, and
 * the refresh endpoint needs the universe at runtime.
 *
 * tests/collection-universe.test.ts asserts the two are identical, so they
 * cannot drift: a change to the experiment universe fails the build until this
 * file is regenerated. Do not edit either by hand to "fix" that test — the
 * universe is frozen for the duration of the experiment.
 */
export const COLLECTION_UNIVERSE: readonly string[] = [
  "Danger Zone Case",
  "Dreams & Nightmares Case",
  "Kilowatt Case",
  "Recoil Case",
  "Fracture Case",
  "Clutch Case",
  "Fever Case",
  "Chroma 2 Case",
  "Spectrum 2 Case",
  "Operation Breakout Weapon Case",
  "Glove Case",
  "Operation Broken Fang Case",
  "Shattered Web Case",
  "Operation Riptide Case",
  "eSports 2013 Case",
  "CS:GO Weapon Case",
  "Operation Bravo Case",
  "Operation Hydra Case",
  "Huntsman Weapon Case",
  "Winter Offensive Weapon Case",
  "Sticker | Team Liquid | Paris 2023",
  "Paris 2023 Contenders Sticker Capsule",
  "Budapest 2025 Legends Sticker Capsule",
  "Antwerp 2022 Legends Sticker Capsule",
  "Stockholm 2021 Challengers Sticker Capsule",
  "Sticker | High Heat",
  "Sticker | Winding Scorch (Foil)",
  "Sticker Capsule 2",
  "Stockholm 2021 Legends Sticker Capsule",
  "Sticker | Dragon Lore (Foil)",
  "Sticker | Titan | Cluj-Napoca 2015",
  "Sticker | Crown (Foil)",
  "Sticker | Virtus.pro | Katowice 2015",
  "Sticker | 100 Thieves | 2020 RMR",
  "Sticker | Bad News Eagles | Paris 2023",
  "Sticker | iBUYPOWER | Cologne 2014",
  "Sticker | Titan (Holo) | Cologne 2014",
  "Sticker | iBUYPOWER (Holo) | Cologne 2014",
  "Sticker | Howling Dawn",
  "Sticker | Reason Gaming (Holo) | Katowice 2014",
  "SSG 08 | Acid Fade (Factory New)",
  "AK-47 | Crane Flight (Field-Tested)",
  "Desert Eagle | Printstream (Field-Tested)",
  "M4A1-S | Black Lotus (Field-Tested)",
  "AK-47 | Inheritance (Field-Tested)",
  "USP-S | Printstream (Field-Tested)",
  "Glock-18 | Candy Apple (Factory New)",
  "AWP | Atheris (Field-Tested)",
  "AK-47 | Redline (Field-Tested)",
  "AK-47 | Olive Polycam (Factory New)",
  "M4A1-S | Decimator (Field-Tested)",
  "M4A4 | Neo-Noir (Field-Tested)",
  "P250 | Asiimov (Field-Tested)",
  "AWP | Asiimov (Field-Tested)",
  "AK-47 | Vulcan (Field-Tested)",
  "AK-47 | Vulcan (Factory New)",
  "M4A1-S | Blue Phosphor (Factory New)",
  "M4A1-S | Hot Rod (Factory New)",
  "AK-47 | Bloodsport (Field-Tested)",
  "AWP | Atheris (Well-Worn)",
  "AUG | Storm (Field-Tested)",
  "AUG | Contractor (Field-Tested)",
  "P250 | Sand Dune (Minimal Wear)",
  "M4A1-S | Decimator (Battle-Scarred)",
  "Glock-18 | Sand Dune (Field-Tested)",
  "AUG | Hot Rod (Factory New)",
  "AWP | Dragon Lore (Factory New)",
  "AK-47 | Wild Lotus (Factory New)",
  "StatTrak\u2122 M4A4 | Howl (Factory New)",
  "Souvenir AWP | Dragon Lore (Factory New)",
  "\u2605 Bowie Knife | Tiger Tooth (Factory New)",
  "\u2605 Survival Knife",
  "\u2605 Paracord Knife",
  "\u2605 Talon Knife | Tiger Tooth (Factory New)",
  "\u2605 Skeleton Knife | Tiger Tooth (Factory New)",
  "\u2605 Butterfly Knife | Tiger Tooth (Factory New)",
  "\u2605 Kukri Knife | Fade (Factory New)",
  "\u2605 Kukri Knife | Forest DDPAT (Field-Tested)",
  "\u2605 Nomad Knife | Slaughter (Minimal Wear)",
  "\u2605 Bayonet | Forest DDPAT (Field-Tested)",
  "\u2605 Butterfly Knife | Slaughter (Minimal Wear)",
  "\u2605 Navaja Knife | Scorched (Field-Tested)",
  "\u2605 Shadow Daggers | Black Laminate (Battle-Scarred)",
  "\u2605 Karambit | Crimson Web (Factory New)",
  "\u2605 StatTrak\u2122 Navaja Knife | Blue Steel (Factory New)",
  "\u2605 Driver Gloves | Imperial Plaid (Field-Tested)",
  "\u2605 Hand Wraps | Duct Tape (Field-Tested)",
  "\u2605 Driver Gloves | Racing Green (Field-Tested)",
  "\u2605 Driver Gloves | Snow Leopard (Field-Tested)",
  "\u2605 Sport Gloves | Vice (Field-Tested)",
  "\u2605 Sport Gloves | Bronze Morph (Field-Tested)",
  "\u2605 Moto Gloves | Turtle (Field-Tested)",
  "\u2605 Moto Gloves | Turtle (Minimal Wear)",
  "\u2605 Hydra Gloves | Mangrove (Field-Tested)",
  "\u2605 Hand Wraps | Duct Tape (Battle-Scarred)",
  "\u2605 Hydra Gloves | Mangrove (Well-Worn)",
  "\u2605 Specialist Gloves | Fade (Minimal Wear)",
  "\u2605 Sport Gloves | Pandora's Box (Field-Tested)",
  "\u2605 Moto Gloves | Spearmint (Minimal Wear)",
  "\u2605 Sport Gloves | Vice (Factory New)",
];
